#!/usr/bin/env bash

if [[ $1 == "venv" ]]; then
    if [[ $2 == "-e" || $2 == "--environment" ]]; then
        ENV_FILE=$3
    else
        ENV_FILE=env.yml
    fi

    if [[ ! -f $ENV_FILE ]]; then
        echo Environment file $ENV_FILE not found
        exit 1
    fi

    echo export AWS_PROFILE=`yq .aws.profile $ENV_FILE`
    echo export AWS_REGION=`yq .aws.region $ENV_FILE`

    echo export TF_VAR_region=$AWS_REGION
    echo export TF_VAR_project=`yq .metadata.project $ENV_FILE`
fi

if [[ $1 == "init" ]]; then
    echo Some init
fi


if [[ $1 == "sso" ]]; then
    echo Some SSO
fi

if [[ $1 == "version" ]]; then
    echo Terraform version
    terraform version
fi

if [[ $* == "-h" || -z "$1" ]]
then
    ME=$(basename $0)
    echo "USAGE:"
    echo "$ME venv"
    echo "$ME init"
    echo "$ME sso"
    echo "$ME version"
    echo
    echo "-h            Show this help"
    return 0 2> /dev/null || exit 0
fi
