#!/usr/bin/env bash

if [[ $1 == "venv" ]]; then
    if [[ $2 == "-e" || $2 == "--environment" ]]; then
        ENV_FILE=$3
    else
        ENV_FILE=env.yml
    fi

    if [[ ! -f $ENV_FILE ]]; then
        echo Environment file $ENV_FILE not found
        exit 1
    fi

    echo Reading environment config from $ENV_FILE 1>&2

    AWS_PROFILE=`yq .aws.profile $ENV_FILE`
    AWS_REGION=`yq .aws.region $ENV_FILE`
    AWS_ACCOUNT_ID=`yq .aws.accountID $ENV_FILE`

    echo 1>&2
    echo Configuring AWS profile $AWS_PROFILE 1>&2

    aws configure set --profile $AWS_PROFILE sso_start_url https://d-936709095d.awsapps.com/start
    aws configure set --profile $AWS_PROFILE sso_region eu-west-1
    aws configure set --profile $AWS_PROFILE sso_account_id $AWS_ACCOUNT_ID
    aws configure set --profile $AWS_PROFILE sso_role_name AWSAdministratorAccess
    aws configure set --profile $AWS_PROFILE region $AWS_REGION
    aws configure set --profile $AWS_PROFILE output json

    echo 1>&2
    echo Logging into AWS SSO 1>&2
    echo 1>&2

    aws sso login --profile $AWS_PROFILE 1>&2

    echo export AWS_PROFILE=$AWS_PROFILE
    echo export AWS_REGION=$AWS_REGION

    echo export TF_VAR_region=$AWS_REGION
    echo export TF_VAR_project=`yq .metadata.project $ENV_FILE`
fi

if [[ $1 == "init" ]]; then
    echo Some init
fi


if [[ $1 == "sso" ]]; then
    echo Some SSO
fi

if [[ $1 == "version" ]]; then
    echo Terraform version
    terraform version
fi

if [[ $* == "-h" || -z "$1" ]]
then
    ME=$(basename $0)
    echo "USAGE:"
    echo "$ME venv"
    echo "$ME init"
    echo "$ME sso"
    echo "$ME version"
    echo
    echo "-h            Show this help"
    return 0 2> /dev/null || exit 0
fi
